import { StyleSheet } from "react-native";

const fassrollerScale = 85

const colors = {
    darkBGColor: '#2b2b2b',
    darkAccColor: '#00417d',
    darkSheetColor: '#252525',
    darkSheetHandleColor: '#1b1b1b',
    darkDrinkColor: '#252525',
    dbTextColor: '#fff',
    darkRippleColor: '#aaaaaa',
    
    blueBGColor: '#004280',
    blueAccBGColor: '#003363',
    blueSheetColor: '#00203d',
    blueSheetHandleColor: '#001427',
    blueDrinkColor: '#00203d',
    blueRippleColor: '#003D75',
    
    lightBGColor: '#e6e6e6',
    lightTextColor: '#000',
    lightAccColor: '#0053a0',
    lightSheetColor: '#e6e6e6',
    lightSheetHandleColor: '#c0c0c0',
    // lightDrinkColor: '#e6e6e6',
    lightDrinkColor: '#0053a0',
    lightRippleColor: '#c0c0c0',
}

export const dark = StyleSheet.create({
    name: 'dark',
    sheetColor: colors.darkSheetColor,
    sheetHandleColor: colors.darkSheetHandleColor,
    sheetHandleIndicatorColor: colors.dbTextColor,
    textColor: colors.dbTextColor,
    accentColor: colors.darkAccColor,
    drinkColor: colors.darkDrinkColor,
    rippleColor: colors.darkRippleColor,
    container: {
        flex: 1,
        backgroundColor: colors.darkBGColor,
    },
    content: {
        flex: 1,
        paddingBottom: 50,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
    },
    text: {
        fontWeight: 'bold',
        fontSize: 30,
        color: colors.dbTextColor,
        marginTop: 53,
        marginBottom: 15,
        marginHorizontal: 20,
        textAlignVertical: 'center',
    },
    countSudoku: {
        fontWeight: 'bold',
        fontSize: 40,
        color: colors.dbTextColor,
        marginBottom: 25,
        marginTop: 15,
        marginHorizontal: 20,
        backgroundColor: colors.darkAccColor,
        borderRadius: 5,
        textAlignVertical: 'center',
        textAlign: 'center',
        paddingHorizontal: 20,
        paddingBottom: 2,
    },
    fassroller: {
        width: fassrollerScale,
        height: fassrollerScale,
        color: colors.blueBGColor,
    },
    icon: {
        color: colors.dbTextColor,
        fontSize: 40,
        padding: 3, 
        paddingVertical: 8,
        textAlign: 'center',
        textAlignVertical: 'center',
    }
});

export const blue = StyleSheet.create({
    name: 'blue',
    sheetColor: colors.blueSheetColor,
    sheetHandleColor: colors.blueSheetHandleColor,
    sheetHandleIndicatorColor: colors.dbTextColor,
    textColor: colors.dbTextColor,
    accentColor: colors.blueAccBGColor,
    drinkColor: colors.blueDrinkColor,
    rippleColor: colors.blueRippleColor,
    container: {
      flex: 1,
      backgroundColor: colors.blueBGColor,
    },
    content: {
      flex: 1,
      paddingBottom: 50,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'space-between',
    },
    text: {
      fontWeight: 'bold',
      fontSize: 30,
      color: colors.dbTextColor,
      marginTop: 53,
      marginBottom: 15,
      marginHorizontal: 20,
      textAlignVertical: 'center',
    },
    countSudoku: {
      fontWeight: 'bold',
      fontSize: 40,
      color: colors.dbTextColor,
      marginBottom: 25,
      marginTop: 15,
      marginHorizontal: 20,
      backgroundColor: colors.blueAccBGColor,
      borderRadius: 5,
      textAlignVertical: 'center',
      textAlign: 'center',
      paddingHorizontal: 20,
      paddingBottom: 2,
    },
    fassroller: {
      width: fassrollerScale,
      height: fassrollerScale,
      color: '#fff'
    },
    icon: {
      color: colors.dbTextColor,
      fontSize: 40,
      padding: 3, 
      paddingVertical: 8,
      textAlign: 'center',
      textAlignVertical: 'center',
    }
});

export const light = StyleSheet.create({
    name: 'light',
    sheetColor: colors.lightSheetColor,
    sheetHandleColor: colors.lightSheetHandleColor,
    sheetHandleIndicatorColor: colors.lightTextColor,
    textColor: colors.lightTextColor,
    accentColor: colors.lightAccColor,
    drinkColor: colors.lightDrinkColor,
    rippleColor: colors.lightRippleColor,
    container: {
      flex: 1,
      backgroundColor: colors.lightBGColor,
    },
    content: {
      flex: 1,
      paddingBottom: 50,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'space-between',
    },
    text: {
      fontWeight: 'bold',
      fontSize: 30,
      color: colors.lightTextColor,
      marginTop: 53,
      marginBottom: 15,
      marginHorizontal: 20,
      textAlignVertical: 'center',
    },
    countSudoku: {
      fontWeight: 'bold',
      fontSize: 40,
      color: colors.lightBGColor,
      marginBottom: 25,
      marginTop: 15,
      marginHorizontal: 20,
      backgroundColor: colors.lightAccColor,
      borderRadius: 5,
      textAlignVertical: 'center',
      textAlign: 'center',
      paddingHorizontal: 20,
      paddingBottom: 2,
    },
    fassroller: {
      width: fassrollerScale,
      height: fassrollerScale,
      color: colors.lightAccColor,
    },
    icon: {
      color: colors.lightTextColor,
      fontSize: 40,
      padding: 3, 
      paddingVertical: 8,
      textAlign: 'center',
      textAlignVertical: 'center',
    }
});